<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<link type="text/css" rel="stylesheet" media="all" href="css/master.css" />
<script src="js/_libs/jquery-1.8.3.min.js"></script>  
</head>
<body>

	<div id="header">
		<div id="logo">
			<img src="/images/logo.jpg" />
		</div>
		
		<ul id="menu">
			<li><a href="#">Главная</a></li>
			<li><a href="#">Услуги</a></li>
			<li><a href="#">Контакты</a></li>
		</ul>
	</div>
	
	<div id="content">
		<?php echo $this->layout()->content ?>
	</div>
	
	<div id="footer">
		<div>Copyright 2012</div>
	</div>
</body>
</html>